# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: push

jobs:
  build-app1:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./app1
    - run: npm run build
      working-directory: ./app1
    - uses: actions/upload-artifact@v1
      with:
        name: app1-build
        path: ./app1/dist

  build-app2:
    needs: build-app1
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/download-artifact@v1
      with:
        name: app1-build
        path: ./app1
    - run: npm i ../app1
      working-directory: ./app2
    - run: npm ci
      working-directory: ./app2
    - run: npm run build
      working-directory: ./app2
    - uses: actions/upload-artifact@v1
      with:
        name: app2-build
        path: ./app2/dist

  build-app3:
    needs: build-app1
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/download-artifact@v1
      with:
        name: app1-build
        path: ./app3
    - run: npm i ../app1
      working-directory: ./app3
    - run: npm ci
      working-directory: ./app3
    - run: npm run build
      working-directory: ./app3
    - uses: actions/upload-artifact@v1
      with:
        name: app3-build
        path: ./app3/dist