# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: 
      - release/**

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: npm run typedoc
      - run: |
         git add docs/*
         git config --global user.email "you@example.com"
         git config --global user.name "CI"
         git commit -m "docs(*): regenerate type documentation"
      - run: npm version patch --no-git-tag-version
        if: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/patch'))
        name: 'increase patch version'
      - run: npm version patch --no-git-tag-version
        if: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/patch'))
        name: 'increase patch version'
      - run: npm version patch --no-git-tag-version
        if: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/patch'))
        name: 'increase patch version'
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - run: npm version --no-git-tag-version {{ steps.extract_version.outputs.version }}
        working-directory: ./app1
      - run: npm version --no-git-tag-version {{ steps.extract_version.outputs.version }}
        working-directory: ./app2
      - run: npm version --no-git-tag-version {{ steps.extract_version.outputs.version }}
        working-directory: ./app3
      - run: git add .package.json ./app1/package.json ./app2/package.json ./app3/package.json
      - run: "git commit -m 'chore(*): update app to version {{steps.extract_version.outputs.version}}'"
      - run: git push
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#       - run: npm ci
#       - run: npm test

#   publish-npm:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://registry.npmjs.org/
#       - run: npm ci
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.npm_token}}

#   publish-gpr:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 12
#           registry-url: https://npm.pkg.github.com/
#           scope: '@your-github-username'
#       - run: npm ci
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
