# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: ready-to-release

on:
  pull_request:
    branches:
      - master
    types: [labeled]

jobs:
  update-version:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ready-to-deploy'
    steps:
      - uses: mdecoleman/pr-branch-name@1.0.0
        id: branch-name
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.branch-name.outputs.branch }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git fetch
      - run: npm i
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "CI"
      - run: npm run release
      - run: |
          git push
          git push origin --tags
