# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Merge+Release

on:
  pull_request:
    branches:
      - 'release/**'
    types: [labeled]

jobs:
  has-label:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v1
        with:
          allowed: >
            ready-to-deploy
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Starting release :rocket Please do not merge into this branch anymore!'

  update-version:
    runs-on: ubuntu-latest
    needs: has-label
    steps:
      # - uses: actions/download-artifact@v1
      #   with:
      #     name: branch-name
      #     path: ./
      # - run: echo "##[set-output name=branch-name;]$(cat ./branch-name.txt)"
      #   id: branch-name
      # - run: rm ./branch-name.txt
      - uses: actions/checkout@v2
        # with:
        #   ref: ${{steps.branch-name.outputs.branch-name}}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: |
          git config --global user.email "you@example.com"
          git config --global user.name "CI"
      - run: npm run release
      - run: git push

  merge:
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: Pull Request Merginator
        uses: managedkaos/merge-pull-request@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Merged into Master. Please merge "-> develop" PR and delete the branch.'

